bug:
  - fix/*
chore:
  - chore/*
ci:
  - ci/*
documentation:
  - docs/*
  - documentation/*
enhancement:
  - feat/*
  - feature/*
refactor:
  - refactor/*
revert:
  - revert/*
  - revert-*
style:
  - style/*
test:
  - test/*
