// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf3IWZvgghERJZgUcli2fQD-UlTW_INjg',
    appId: '1:90034869484:web:3f2deccb3299aafa8081c9',
    messagingSenderId: '90034869484',
    projectId: 'appainter-2720d',
    authDomain: 'appainter-2720d.firebaseapp.com',
    storageBucket: 'appainter-2720d.appspot.com',
    measurementId: 'G-R2WXGL9BL5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvBBZnA2obYYbNPqNVCpjOlZsLQUmIi_k',
    appId: '1:90034869484:ios:5a4a55aa6ae64a348081c9',
    messagingSenderId: '90034869484',
    projectId: 'appainter-2720d',
    storageBucket: 'appainter-2720d.appspot.com',
    iosClientId:
        '90034869484-dv46071etje7r98biqqht4701gvqq3mm.apps.googleusercontent.com',
    iosBundleId: 'dev.appainter',
  );
}
