name: appainter_annotations
description: Annotations for generating theme documentations
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0
