name: Check Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-title:
    name: Check Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic pull request
        uses: amannn/action-semantic-pull-request@v4.0.1
        with:
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
