name: Check Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    name: Check Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic pull request
        uses: amannn/action-semantic-pull-request@v3.6.0
        with:
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
