name: Close Stale Issues and Pull Requests

on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  close-stale:
    name: Close Stale
    runs-on: ubuntu-latest
    steps:
      - name: Stale
        uses: actions/stale@v7
        with:
          days-before-issue-stale: 3
          days-before-issue-close: 2
          only-labels: question
          stale-issue-label: stale
          close-issue-message: This issue has been automatically closed due to inactivity. Feel free to comment in order to reopen.
