name: Pull request target actions

on:
  pull_request_target:

jobs:
  pull-request:
    uses: zeshuaro/github-actions-workflows/.github/workflows/pull-request-target.yml@6b595f809ac29049e8af015cb95632f31ff5f370
